### ISSUE TITLE
error log VoteBKM_2.2_beta

### ISSUE THREAD

**Issue by mrdiega** [ebpnk/VoteBKM#5]
`Error handling player disconnect: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`
![image](https://github.com/ebpnk/VoteBKM/assets/79888956/e2c35c47-8ca2-413d-a4c2-208550a43f10)

**Comment by lugaamn** [comment]
Can I stop players from getting admins with votekick votes with this plugin?
Provides immunity to protect admin from VOTEKICK suggestions.
As in CS:GO https://forums.alliedmods.net/showthread.php?t=161586 like this

**Comment by mrdiega** [comment]
In addition, server crashes when the map changes
